import "./styles/global.scss";

export const metadata = {
    title: "Task Manager",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    );
}
